config/routes.rb
Rails.application.routes.draw do
  resources :project_members

  resources :project_phases

  resources :projects

  resources :resources

  root 'resources#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/project_member.rb
class ProjectMember < ActiveRecord::Base
  belongs_to :project_phase
  belongs_to :resource
end

app/models/project_phase.rb
class ProjectPhase < ActiveRecord::Base
  belongs_to :project
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale

  layout 'application'

  private

#    def default_url_options(options={})
#      { :language => I18n.locale }
#    end

    def set_locale
      logger.debug "* Accept-Language: #{request.env['HTTP_ACCEPT_LANGUAGE']}"
      I18n.locale = extract_locale_from_accept_language_header
      logger.debug "* Locale set to '#{I18n.locale}'"
    end

    def extract_locale_from_accept_language_header
      request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
    end

end

app/controllers/project_members_controller.rb
class ProjectMembersController < ApplicationController
  before_action :set_project_member, only: [:show, :edit, :update, :destroy]

  # GET /project_members
  def index
    @project_members = ProjectMember.all
  end

  # GET /project_members/1
  def show
  end

  # GET /project_members/new
  def new
    @project_member = ProjectMember.new
  end

  # GET /project_members/1/edit
  def edit
  end

  # POST /project_members
  def create
    @project_member = ProjectMember.new(project_member_params)

    if @project_member.save
      redirect_to @project_member, notice: t('flash.actions.create.notice', model: ProjectMember.model_name.human( :count=>1 ) )
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /project_members/1
  def update
    if @project_member.update(project_member_params)
      redirect_to @project_member, notice: t('flash.actions.update.notice', model: ProjectMember.model_name.human( :count=>1 ) )
    else
      render action: 'edit'
    end
  end

  # DELETE /project_members/1
  def destroy
    @project_member.destroy
    redirect_to project_members_url, notice: t('flash.actions.delete.notice', model: ProjectMember.model_name.human( :count=>1 ) )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_member
      @project_member = ProjectMember.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_member_params
      params.require(:project_member).permit(:project_phase_id, :resource_id)
    end
end

app/controllers/project_phases_controller.rb
class ProjectPhasesController < ApplicationController
  before_action :set_project_phase, only: [:show, :edit, :update, :destroy]

  # GET /project_phases
  def index
    @project_phases = ProjectPhase.all
  end

  # GET /project_phases/1
  def show
  end

  # GET /project_phases/new
  def new
    @project_phase = ProjectPhase.new
  end

  # GET /project_phases/1/edit
  def edit
  end

  # POST /project_phases
  def create
    @project_phase = ProjectPhase.new(project_phase_params)

    if @project_phase.save
      redirect_to @project_phase, notice: t('flash.actions.create.notice', model: ProjectPhase.model_name.human( :count=>1 ) )
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /project_phases/1
  def update
    if @project_phase.update(project_phase_params)
      redirect_to @project_phase, notice: t('flash.actions.update.notice', model: ProjectPhase.model_name.human( :count=>1 ) )
    else
      render action: 'edit'
    end
  end

  # DELETE /project_phases/1
  def destroy
    @project_phase.destroy
    redirect_to project_phases_url, notice: t('flash.actions.delete.notice', model: ProjectPhase.model_name.human( :count=>1 ) )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_phase
      @project_phase = ProjectPhase.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_phase_params
      params.require(:project_phase).permit(:project_id, :name, :start, :end)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: t('flash.actions.create.notice', model: Project.model_name.human( :count=>1 ) )
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: t('flash.actions.update.notice', model: Project.model_name.human( :count=>1 ) )
    else
      render action: 'edit'
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: t('flash.actions.delete.notice', model: Project.model_name.human( :count=>1 ) )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:name, :start, :end)
    end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  # GET /resources
  def index
    @resources = Resource.all
  end

  # GET /resources/1
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  def create
    @resource = Resource.new(resource_params)

    if @resource.save
      redirect_to @resource, notice: t('flash.actions.create.notice', model: Resource.model_name.human( :count=>1 ) )
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /resources/1
  def update
    if @resource.update(resource_params)
      redirect_to @resource, notice: t('flash.actions.update.notice', model: Resource.model_name.human( :count=>1 ) )
    else
      render action: 'edit'
    end
  end

  # DELETE /resources/1
  def destroy
    @resource.destroy
    redirect_to resources_url, notice: t('flash.actions.delete.notice', model: Resource.model_name.human( :count=>1 ) )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def resource_params
      params.require(:resource).permit(:first_name, :last_name, :start)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def l(d)
    d ? I18n.l(d) : ""
  end

end

app/helpers/project_members_helper.rb
module ProjectMembersHelper
end

app/helpers/project_phases_helper.rb
module ProjectPhasesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/layouts/_menu.html.erb
<%= nav_bar :fixed => :top, :brand => t('title') do %>
  <% menu_group do %>
    <%= drop_down t('activerecord.models.resource.other') do %>
      <%= menu_item t('helpers.titles.index', model: Resource.model_name.human( :count => 2 ) ), resources_path %>
      <%= menu_item t('helpers.titles.new', model: Resource.model_name.human), new_resource_path %>
    <% end %>
    <%= drop_down t('activerecord.models.project.other') do %>
      <%= menu_item t('helpers.titles.index', model: Project.model_name.human( :count => 2 ) ), projects_path %>
      <%= menu_item t('helpers.titles.new', model: Project.model_name.human), new_project_path %>
    <% end %>
    <%= drop_down t('activerecord.models.project_phase.other') do %>
      <%= menu_item t('helpers.titles.index', model: ProjectPhase.model_name.human( :count => 2 ) ), project_phases_path %>
      <%= menu_item t('helpers.titles.new', model: ProjectPhase.model_name.human), new_project_phase_path %>
    <% end %>
    <%= drop_down t('activerecord.models.project_member.other') do %>
      <%= menu_item t('helpers.titles.index', model: ProjectMember.model_name.human( :count => 2 ) ), project_members_path %>
      <%= menu_item t('helpers.titles.new', model: ProjectMember.model_name.human), new_project_member_path %>
    <% end %>
    <%= menu_item t('menu.about'), page_path('about') %>
    <%= menu_item t('menu.contact'), page_path('contact') %>
   <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BootstrapDatepickerEnhancedExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/menu' %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<h1><%= t('menu.about') %></h1>
<p>
YourProgramm
</p>
<hr/>
<p>
YourDescription
</p>

app/views/pages/contact.html.erb
<h1><%= t('menu.contact') %></h1>
<p>
(c) YourName, 2013
</p>
<hr/>
<p>
YourName<br/>
YourAddress
</p>

app/views/project_members/_form.html.erb
<%= form_for(@project_member) do |f| %>
  <% if @project_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_member.errors.count, "error") %> prohibited this project_member from being saved:</h2>
      <ul>
        <% @project_member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inputs">
    <div class="field">
      <%= f.label :project_phase_id %>
      <%= f.text_field :project_phase_id %>
    </div>
    <div class="field">
      <%= f.label :resource_id %>
      <%= f.text_field :resource_id %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_members/edit.html.erb
<h1><%= t('helpers.titles.edit', model: Project Member.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('helpers.links.show'), @project_member %> |
<%= link_to t('helpers.links.back'), project_members_path %>

app/views/project_members/index.html.erb
<h1><%= t('helpers.titles.index', model: ProjectMember.model_name.human( :count=>2 ) ) %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.project_member.project_phase') %></th>
      <th><%= t('activerecord.attributes.project_member.resource') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @project_members.each do |project_member| %>
      <tr>
        <td><%= project_member.project_phase %></td>
        <td><%= project_member.resource %></td>
        <td><%= link_to t('helpers.links.show'), project_member %></td>
        <td><%= link_to t('helpers.links.edit'), edit_project_member_path(project_member) %></td>
        <td><%= link_to t('helpers.links.destroy'), project_member, method: :delete, data: { confirm: t('helpers.links.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to t('helpers.titles.new', model: ProjectMember.model_name.human ), new_project_member_path %></p>

app/views/project_members/new.html.erb
<h1><%= t('helpers.titles.new', model: ProjectMember.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('helpers.links.back'), project_members_path %>

app/views/project_members/show.html.erb
<h1><%= t('helpers.titles.show', model: ProjectMember.model_name.human ) %></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.project_member.project_phase') %>:</strong>
  <%= @project_member.project_phase %>
</p>
<p>
  <strong><%= t('activerecord.attributes.project_member.resource') %>:</strong>
  <%= @project_member.resource %>
</p>

<%= link_to t('helpers.links.edit'), edit_project_member_path(@project_member) %> |
<%= link_to t('helpers.links.view_all'), project_members_path %>

app/views/project_phases/_form.html.erb
<%= form_for(@project_phase) do |f| %>
  <% if @project_phase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_phase.errors.count, "error") %> prohibited this project_phase from being saved:</h2>
      <ul>
        <% @project_phase.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inputs">
    <div class="field">
      <%= f.label :project_id %>
      <%= f.text_field :project_id %>
    </div>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :start %>
      <%= f.text_field :start, :input_html => { :size => 10, :maxlength => 10, :language => I18n.locale }, :'data-behaviour' => :datepicker %>
    </div>
    <div class="field">
      <%= f.label :end %>
      <%= f.text_field :end, :input_html => { :size => 10, :maxlength => 10, :language => I18n.locale }, :'data-behaviour' => :datepicker %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_phases/edit.html.erb
<h1><%= t('helpers.titles.edit', model: Project Phase.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('helpers.links.show'), @project_phase %> |
<%= link_to t('helpers.links.back'), project_phases_path %>

app/views/project_phases/index.html.erb
<h1><%= t('helpers.titles.index', model: ProjectPhase.model_name.human( :count=>2 ) ) %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.project_phase.project') %></th>
      <th><%= t('activerecord.attributes.project_phase.name') %></th>
      <th><%= t('activerecord.attributes.project_phase.start') %></th>
      <th><%= t('activerecord.attributes.project_phase.end') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @project_phases.each do |project_phase| %>
      <tr>
        <td><%= project_phase.project %></td>
        <td><%= project_phase.name %></td>
        <td><%= l project_phase.start %></td>
        <td><%= l project_phase.end %></td>
        <td><%= link_to t('helpers.links.show'), project_phase %></td>
        <td><%= link_to t('helpers.links.edit'), edit_project_phase_path(project_phase) %></td>
        <td><%= link_to t('helpers.links.destroy'), project_phase, method: :delete, data: { confirm: t('helpers.links.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to t('helpers.titles.new', model: ProjectPhase.model_name.human ), new_project_phase_path %></p>

app/views/project_phases/new.html.erb
<h1><%= t('helpers.titles.new', model: ProjectPhase.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('helpers.links.back'), project_phases_path %>

app/views/project_phases/show.html.erb
<h1><%= t('helpers.titles.show', model: ProjectPhase.model_name.human ) %></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.project_phase.project') %>:</strong>
  <%= @project_phase.project %>
</p>
<p>
  <strong><%= t('activerecord.attributes.project_phase.name') %>:</strong>
  <%= @project_phase.name %>
</p>
<p>
  <strong><%= t('activerecord.attributes.project_phase.start') %>:</strong>
  <%= l @project_phase.start %>
</p>
<p>
  <strong><%= t('activerecord.attributes.project_phase.end') %>:</strong>
  <%= l @project_phase.end %>
</p>

<%= link_to t('helpers.links.edit'), edit_project_phase_path(@project_phase) %> |
<%= link_to t('helpers.links.view_all'), project_phases_path %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inputs">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :start %>
      <%= f.text_field :start, :input_html => { :size => 10, :maxlength => 10, :language => I18n.locale }, :'data-behaviour' => :datepicker %>
    </div>
    <div class="field">
      <%= f.label :end %>
      <%= f.text_field :end, :input_html => { :size => 10, :maxlength => 10, :language => I18n.locale }, :'data-behaviour' => :datepicker %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1><%= t('helpers.titles.edit', model: Project.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('helpers.links.show'), @project %> |
<%= link_to t('helpers.links.back'), projects_path %>

app/views/projects/index.html.erb
<h1><%= t('helpers.titles.index', model: Project.model_name.human( :count=>2 ) ) %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.project.name') %></th>
      <th><%= t('activerecord.attributes.project.start') %></th>
      <th><%= t('activerecord.attributes.project.end') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= l project.start %></td>
        <td><%= l project.end %></td>
        <td><%= link_to t('helpers.links.show'), project %></td>
        <td><%= link_to t('helpers.links.edit'), edit_project_path(project) %></td>
        <td><%= link_to t('helpers.links.destroy'), project, method: :delete, data: { confirm: t('helpers.links.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to t('helpers.titles.new', model: Project.model_name.human ), new_project_path %></p>

app/views/projects/new.html.erb
<h1><%= t('helpers.titles.new', model: Project.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('helpers.links.back'), projects_path %>

app/views/projects/show.html.erb
<h1><%= t('helpers.titles.show', model: Project.model_name.human ) %></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.project.name') %>:</strong>
  <%= @project.name %>
</p>
<p>
  <strong><%= t('activerecord.attributes.project.start') %>:</strong>
  <%= l @project.start %>
</p>
<p>
  <strong><%= t('activerecord.attributes.project.end') %>:</strong>
  <%= l @project.end %>
</p>

<%= link_to t('helpers.links.edit'), edit_project_path(@project) %> |
<%= link_to t('helpers.links.view_all'), projects_path %>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>
      <ul>
        <% @resource.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inputs">
    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :start %>
      <%= f.text_field :start, :input_html => { :size => 10, :maxlength => 10, :language => I18n.locale }, :'data-behaviour' => :datepicker %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1><%= t('helpers.titles.edit', model: Resource.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('helpers.links.show'), @resource %> |
<%= link_to t('helpers.links.back'), resources_path %>

app/views/resources/index.html.erb
<h1><%= t('helpers.titles.index', model: Resource.model_name.human( :count=>2 ) ) %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.resource.first_name') %></th>
      <th><%= t('activerecord.attributes.resource.last_name') %></th>
      <th><%= t('activerecord.attributes.resource.start') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.first_name %></td>
        <td><%= resource.last_name %></td>
        <td><%= l resource.start %></td>
        <td><%= link_to t('helpers.links.show'), resource %></td>
        <td><%= link_to t('helpers.links.edit'), edit_resource_path(resource) %></td>
        <td><%= link_to t('helpers.links.destroy'), resource, method: :delete, data: { confirm: t('helpers.links.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to t('helpers.titles.new', model: Resource.model_name.human ), new_resource_path %></p>

app/views/resources/new.html.erb
<h1><%= t('helpers.titles.new', model: Resource.model_name.human ) %></h1>

<%= render 'form' %>

<%= link_to t('helpers.links.back'), resources_path %>

app/views/resources/show.html.erb
<h1><%= t('helpers.titles.show', model: Resource.model_name.human ) %></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.resource.first_name') %>:</strong>
  <%= @resource.first_name %>
</p>
<p>
  <strong><%= t('activerecord.attributes.resource.last_name') %>:</strong>
  <%= @resource.last_name %>
</p>
<p>
  <strong><%= t('activerecord.attributes.resource.start') %>:</strong>
  <%= l @resource.start %>
</p>

<%= link_to t('helpers.links.edit'), edit_resource_path(@resource) %> |
<%= link_to t('helpers.links.view_all'), resources_path %>